// <auto-generated />
using Mango.Services.CategoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CategoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241024143912_Add sample data for categories")]
    partial class Addsampledataforcategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CategoryAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageLocalPath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Kimchi",
                            ImageLocalPath = "wwwroot\\CategoryImages\\1.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/1.png"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Jjigae",
                            ImageLocalPath = "wwwroot\\CategoryImages\\2.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/2.png"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Banchan",
                            ImageLocalPath = "wwwroot\\CategoryImages\\3.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/3.png"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bulgogi and Gui",
                            ImageLocalPath = "wwwroot\\CategoryImages\\4.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/4.png"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Tteok",
                            ImageLocalPath = "wwwroot\\CategoryImages\\5.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/5.png"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Jeon",
                            ImageLocalPath = "wwwroot\\CategoryImages\\6.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/6.png"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Guksu",
                            ImageLocalPath = "wwwroot\\CategoryImages\\7.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/7.png"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Jjim",
                            ImageLocalPath = "wwwroot\\CategoryImages\\8.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/8.png"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Bibimbap",
                            ImageLocalPath = "wwwroot\\CategoryImages\\9.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/9.png"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Anju",
                            ImageLocalPath = "wwwroot\\CategoryImages\\10.png",
                            ImageUrl = "https://localhost:7005/CategoryImages/10.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
