// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026145212_Initial DB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Traditional napa cabbage kimchi, made with salted cabbage, chili flakes, garlic, and fermented seafood.",
                            ImageLocalPath = "wwwroot/ProductImages/1.png",
                            ImageUrl = "https://localhost:7000/ProductImages/1.png",
                            Name = "Baechu Kimchi",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Cubed radish kimchi, crunchy and spicy, usually served with soups and stews.",
                            ImageLocalPath = "wwwroot/ProductImages/2.png",
                            ImageUrl = "https://localhost:7000/ProductImages/2.png",
                            Name = "Kkakdugi",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "White kimchi, a non-spicy version made without chili pepper, offering a mild and refreshing flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/3.png",
                            ImageUrl = "https://localhost:7000/ProductImages/3.png",
                            Name = "Baek Kimchi",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Spicy kimchi stew, typically made with aged kimchi, pork, tofu, and vegetables, simmered in a rich broth.",
                            ImageLocalPath = "wwwroot/ProductImages/4.png",
                            ImageUrl = "https://localhost:7000/ProductImages/4.png",
                            Name = "Kimchi Jjigae",
                            Price = 8.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Fermented soybean paste stew with vegetables, tofu, and sometimes clams or anchovies, offering a savory and umami-rich flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/5.png",
                            ImageUrl = "https://localhost:7000/ProductImages/5.png",
                            Name = "Doenjang Jjigae",
                            Price = 7.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Soft tofu stew with seafood or pork, featuring a spicy broth and silky soft tofu.",
                            ImageLocalPath = "wwwroot/ProductImages/6.png",
                            ImageUrl = "https://localhost:7000/ProductImages/6.png",
                            Name = "Sundubu Jjigae",
                            Price = 8.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Stir-fried glass noodles with vegetables, soy sauce, and sesame oil, often served as a side dish or appetizer.",
                            ImageLocalPath = "wwwroot/ProductImages/7.png",
                            ImageUrl = "https://localhost:7000/ProductImages/7.png",
                            Name = "Japchae",
                            Price = 7.0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Seasoned bean sprout salad, lightly blanched and tossed with sesame oil, garlic, and salt.",
                            ImageLocalPath = "wwwroot/ProductImages/8.png",
                            ImageUrl = "https://localhost:7000/ProductImages/8.png",
                            Name = "Kongnamul Muchim",
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Stir-fried kimchi, often with pork or tuna, giving a smoky and intense flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/9.png",
                            ImageUrl = "https://localhost:7000/ProductImages/9.png",
                            Name = "Kimchi Bokkeum",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Description = "Thinly sliced marinated beef, grilled or stir-fried, served with rice and various side dishes.",
                            ImageLocalPath = "wwwroot/ProductImages/10.png",
                            ImageUrl = "https://localhost:7000/ProductImages/10.png",
                            Name = "Bulgogi",
                            Price = 12.0
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Description = "Grilled pork belly, typically enjoyed with lettuce wraps, garlic, and ssamjang (a savory dipping sauce).",
                            ImageLocalPath = "wwwroot/ProductImages/11.png",
                            ImageUrl = "https://localhost:7000/ProductImages/11.png",
                            Name = "Samgyeopsal",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            Description = "Marinated beef short ribs, either grilled (Galbi Gui) or braised (Galbi Jjim), known for their sweet and savory flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/12.png",
                            ImageUrl = "https://localhost:7000/ProductImages/12.png",
                            Name = "Galbi",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 5,
                            Description = "Spicy stir-fried rice cakes in a gochujang-based sauce, often served with fish cakes and boiled eggs.",
                            ImageLocalPath = "wwwroot/ProductImages/13.png",
                            ImageUrl = "https://localhost:7000/ProductImages/13.png",
                            Name = "Tteokbokki",
                            Price = 7.0
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            Description = "Royal court-style Tteokbokki, featuring a mild soy-based sauce with beef and vegetables.",
                            ImageLocalPath = "wwwroot/ProductImages/14.png",
                            ImageUrl = "https://localhost:7000/ProductImages/14.png",
                            Name = "Gungjung Tteokbokki",
                            Price = 8.0
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 5,
                            Description = "Soft rice cakes coated with roasted soybean powder, offering a chewy texture and nutty flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/15.png",
                            ImageUrl = "https://localhost:7000/ProductImages/15.png",
                            Name = "Injeolmi",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 6,
                            Description = "Savory pancake made with green onions and mixed seafood, served with a soy-vinegar dipping sauce.",
                            ImageLocalPath = "wwwroot/ProductImages/16.png",
                            ImageUrl = "https://localhost:7000/ProductImages/16.png",
                            Name = "Haemul Pajeon",
                            Price = 12.0
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 6,
                            Description = "Kimchi pancake, made with fermented kimchi, flour, and sometimes added pork or seafood.",
                            ImageLocalPath = "wwwroot/ProductImages/17.png",
                            ImageUrl = "https://localhost:7000/ProductImages/17.png",
                            Name = "Kimchi Jeon",
                            Price = 7.0
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 6,
                            Description = "Mung bean pancake with ground mung beans, vegetables, and pork, fried until crispy on the outside.",
                            ImageLocalPath = "wwwroot/ProductImages/18.png",
                            ImageUrl = "https://localhost:7000/ProductImages/18.png",
                            Name = "Bindaetteok",
                            Price = 9.0
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 7,
                            Description = "Cold buckwheat noodles, typically served in a chilled broth (Mul Naengmyeon) or with a spicy sauce (Bibim Naengmyeon).",
                            ImageLocalPath = "wwwroot/ProductImages/19.png",
                            ImageUrl = "https://localhost:7000/ProductImages/19.png",
                            Name = "Naengmyeon",
                            Price = 11.0
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 7,
                            Description = "Noodles in black bean sauce with diced pork and vegetables, known for its rich and slightly sweet flavor.",
                            ImageLocalPath = "wwwroot/ProductImages/20.png",
                            ImageUrl = "https://localhost:7000/ProductImages/20.png",
                            Name = "Jajangmyeon",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 7,
                            Description = "Hand-cut wheat noodles served in a clear broth, usually made with chicken or seafood.",
                            ImageLocalPath = "wwwroot/ProductImages/21.png",
                            ImageUrl = "https://localhost:7000/ProductImages/21.png",
                            Name = "Kalguksu",
                            Price = 14.0
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 8,
                            Description = "Korean rice rolls filled with vegetables, fish, or meat, wrapped in seaweed, perfect for a light meal or snack.",
                            ImageLocalPath = "wwwroot/ProductImages/22.png",
                            ImageUrl = "https://localhost:7000/ProductImages/22.png",
                            Name = "Kimbap",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 8,
                            Description = "Mixed rice with assorted vegetables, meat, and a fried egg, topped with gochujang (spicy red pepper paste).",
                            ImageLocalPath = "wwwroot/ProductImages/23.png",
                            ImageUrl = "https://localhost:7000/ProductImages/23.png",
                            Name = "Bibimbap",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 8,
                            Description = "Korean blood sausage made with pig's blood, rice, and noodles, often served with a spicy dipping sauce.",
                            ImageLocalPath = "wwwroot/ProductImages/24.png",
                            ImageUrl = "https://localhost:7000/ProductImages/24.png",
                            Name = "Sundae",
                            Price = 8.0
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 9,
                            Description = "Sweet Korean pancakes filled with brown sugar, honey, chopped peanuts, and cinnamon, usually served warm.",
                            ImageLocalPath = "wwwroot/ProductImages/25.png",
                            ImageUrl = "https://localhost:7000/ProductImages/25.png",
                            Name = "Hoddeok",
                            Price = 4.0
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 9,
                            Description = "Fish-shaped pastry filled with sweet red bean paste, popular as a street food snack.",
                            ImageLocalPath = "wwwroot/ProductImages/26.png",
                            ImageUrl = "https://localhost:7000/ProductImages/26.png",
                            Name = "Bungeoppang",
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 9,
                            Description = "Korean rice cakes made from glutinous rice flour, often enjoyed during celebrations.",
                            ImageLocalPath = "wwwroot/ProductImages/27.png",
                            ImageUrl = "https://localhost:7000/ProductImages/27.png",
                            Name = "Tteok",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 10,
                            Description = "Deep-fried dough pastries, often coated in cinnamon sugar, typically served with chocolate dipping sauce.",
                            ImageLocalPath = "wwwroot/ProductImages/28.png",
                            ImageUrl = "https://localhost:7000/ProductImages/28.png",
                            Name = "Churros",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 10,
                            Description = "Sweet syrup-filled pancakes, usually served hot and often eaten during the winter.",
                            ImageLocalPath = "wwwroot/ProductImages/29.png",
                            ImageUrl = "https://localhost:7000/ProductImages/29.png",
                            Name = "Hotteok",
                            Price = 4.0
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 10,
                            Description = "Shaved ice dessert topped with sweetened red beans, fruit, and condensed milk, popular in the summer.",
                            ImageLocalPath = "wwwroot/ProductImages/30.png",
                            ImageUrl = "https://localhost:7000/ProductImages/30.png",
                            Name = "Patbingsu",
                            Price = 8.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
